stages:
  quantize:
    cmd: cp pytorch_model.bin pytorch_model.v2.bin
    deps:
    - pytorch_model.bin
    outs:
    - pytorch_model.v2.bin
  gloubi-boulga:
    cmd: date > AGI.bin
    deps:
    - README.md
    - data.xml
    - pytorch_model.v2.bin
    params:
    - seed
    - train.lr
    outs:
    - AGI.bin
  eval:
    cmd: "echo 'f1: 0.99' > scores.yaml"
    deps:
    - AGI.bin
    metrics:
    - scores.yaml:
        cache: false
